<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>isl</string>
	</array>
	<key>name</key>
	<string>Micros</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric_constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords_control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>System variables</string>
			<key>match</key>
			<string>(\@[A-Z_][A-Z0-9_]*)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.win32.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Windows DLL functions</string>
			<key>match</key>
			<string>\b(DLLLoad|DLLCall|DLLFree|DLLCall_CDECL)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>User-defined variables</string>
			<key>match</key>
			<string>\b(var|ref|rxmsg)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.micros</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.micros</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.micros</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.micros</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like foobar: N99</string>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z0-9_]*)(\[([1-9][0-9]*)\])?\s+(:)\s+(([A-Z\$])?([1-9][0-9]*))\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.function.micros</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.micros</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.micros</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.micros</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.micros</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: sub mysub(var a : A20, var b : N32)</string>
			<key>match</key>
			<string>\b(sub)\s+([a-zA-Z_$]\w*)(\s*(\()(.*?)(\)))?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.function.micros</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.micros</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.micros</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.micros</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.micros</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: event inq : 5</string>
			<key>match</key>
			<string>\b(event)\s+([a-zA-Z_$]\w*)(\s+(:)\s+(([A-Z\$])?([1-9][0-9]*)))?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.format.micros</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.micros</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: format Foo as ...</string>
			<key>match</key>
			<string>\b(format)\s+([a-zA-Z_]\w*)\s+\b(as)\b\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.block.end.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(endsub|endevent)\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>built-in functions</string>
			<key>match</key>
			<string>\b(mid|len|key|rxmsg|txmsg)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.delimiter.method.period.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\.</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(|\)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{|\}</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.square.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[|\]</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.micros</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((//).*$\n?)</string>
		</dict>
		<key>keywords_control</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(if|elseif|else|endif|for|endfor|while|endwhile|call|exitwitherror|exitcontinue)\b</string>
		</dict>
		<key>numeric_constants</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.source.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([0-9]+\.?[0-9]*)\b</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.binary.micros</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\*|\/|\%|\+|\-|\&amp;|\||\=|&gt;=|&gt;|&lt;|&lt;=|&lt;&gt;|\b(not|and|or)\b</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.micros</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double-quoted strings</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.micros</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.micros</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.source.micros</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.syntax_name</string>
	<key>uuid</key>
	<string>0b51044e-4929-482f-950b-811e54628ab5</string>
</dict>
</plist>
